ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ dev.gemmabcr.ApplicationKt.module ]
    }
}

db {
    url = "jdbc:postgresql://localhost:5432/app"
    url = ${?DB_URL}
    
    user = "app"
    user = ${?DB_USER}
    
    password = "app"
    password = ${?DB_PASSWORD}
    
    driver = "org.postgresql.Driver"
    driver = ${?DB_DRIVER}
}

oauth {
    publicBaseUrl = "http://localhost:8080"
    publicBaseUrl = ${?PUBLIC_BASE_URL}

    google {
        clientId = ${?GOOGLE_CLIENT_ID}
        clientSecret = ${?GOOGLE_CLIENT_SECRET}
    }

    apple {
        clientId = ${?APPLE_CLIENT_ID}
        clientSecret = ${?APPLE_CLIENT_SECRET}
    }
}
