INSERT INTO toDos (id, description)
VALUES (0, 'Ejemplares alfa capturados'),
       (1, 'Ejemplares avistados saliendo de árboles'),
       (2, 'Ejemplares avistados saliendo de rocas agrietadas'),
       (3, 'Ejemplares capturados'),
       (4, 'Ejemplares capturados durante el día'),
       (5, 'Ejemplares capturados en el aire'),
       (6, 'Ejemplares capturados mientras dormían'),
       (7, 'Ejemplares capturados sin que te detecten'),
       (8, 'Ejemplares capturados por la noche'),
       (138, 'Ejemplares capturados por la tarde'),
       (10, 'Ejemplares derrotados'),
       (11, 'Ejemplares derrotados con movimientos de tipo Acero'),
       (12, 'Ejemplares derrotados con movimientos de tipo Agua'),
       (13, 'Ejemplares derrotados con movimientos de tipo Bicho'),
       (172, 'Ejemplares derrotados con movimientos de tipo Dragón'),
       (14, 'Ejemplares derrotados con movimientos de tipo Eléctrico'),
       (15, 'Ejemplares derrotados con movimientos de tipo Fantasma'),
       (16, 'Ejemplares derrotados con movimientos de tipo Fuego'),
       (17, 'Ejemplares derrotados con movimientos de tipo Hada'),
       (18, 'Ejemplares derrotados con movimientos de tipo Hielo'),
       (19, 'Ejemplares derrotados con movimientos de tipo Lucha'),
       (20, 'Ejemplares derrotados con movimientos de tipo Planta'),
       (21, 'Ejemplares derrotados con movimientos de tipo Psíquico'),
       (22, 'Ejemplares derrotados con movimientos de tipo Roca'),
       (23, 'Ejemplares derrotados con movimientos de tipo Siniestro'),
       (24, 'Ejemplares derrotados con movimientos de tipo Tierra'),
       (132, 'Ejemplares derrotados con movimientos de tipo Veneno'),
       (25, 'Ejemplares derrotados con movimientos de tipo Volador'),
       (26, 'Ejemplares evolucionados'),
       (27, 'Ejemplares grandes capturados'),
       (28, 'Ejemplares ligeros capturados'),
       (29, 'Ejemplares pequeños capturados'),
       (30, 'Ejemplares pesados capturados'),
       (203, 'Has recibido la gracia de Arceus'),
       (31, 'Investiga a los Bidoof que causan estragos por la villa'),
       (165, 'Investiga a los Vulpix de Alola'),
       (189, 'Investiga acerca de la habilidad especial de Swinub'),
       (32, 'Investiga acerca de la seta de Parasect'),
       (33, 'Investiga acerca de las evoluciones de Eevee'),
       (134, 'Investiga acerca del veneno de Croagunk'),
       (34, 'Investiga acerca del sabor de la miel de Combee'),
       (35, 'Investiga al extraño Ponyta'),
       (36, 'Investiga el caso del Blissey samaritano'),
       (181, 'Investiga el caso del Chimecho instalado bajo el alero'),
       (37, 'Investiga el caso del Drifloon que juega con el niño'),
       (38, 'Investiga el caso del Mr.Mime sospechoso'),
       (148, 'Investiga el caso del Sudowoodo alicaído'),
       (176, 'Investiga el proverbio acerca de Nosepass'),
       (140, 'Investiga formas de combatir junto a Pachirisu'),
       (209, 'Investiga la increíble visión nocturna de los Zubat'),
       (40, 'Investiga las diferencias entre Silcoon y Cascoon'),
       (183, 'Investiga si los Clefairy bailan bajo la luz de la luna'),
       (41, 'Variaciones de forma y aspecto avistadas'),
       (42, 'Veces que ha usado movimientos con estilo fuerte'),
       (43, 'Veces que ha usado movimientos con estilo rápido'),
       (44, 'Veces que lo has alimentado'),
       (45, 'Veces que lo has asustado con una Bola Ruidosa'),
       (46, 'Veces que lo has fatigado'),
       (47, 'Veces que lo has visto usar A Bocajarro'),
       (48, 'Veces que lo has visto usar Absorber'),
       (49, 'Veces que lo has visto usar Acua Cola'),
       (50, 'Veces que lo has visto usar Acua Jet'),
       (51, 'Veces que lo has visto usar Aire Afilado'),
       (194, 'Veces que lo has visto usar Ala Aural'),
       (157, 'Veces que lo has visto usar Alarido'),
       (52, 'Veces que lo has visto usar Amortiguador'),
       (144, 'Veces que lo has visto usar Armadura Ácida'),
       (143, 'Veces que lo has visto usar Arremetida'),
       (53, 'Veces que lo has visto usar Asalto Barrera'),
       (54, 'Veces que lo has visto usar Ascuas'),
       (55, 'Veces que lo has visto usar Ataque Rápido'),
       (198, 'Veces que lo has visto usar Aura Magnética'),
       (56, 'Veces que lo has visto usar Autodestrucción'),
       (57, 'Veces que lo has visto usar Avalancha'),
       (204, 'Veces que lo has visto usar Bálsamo Osado'),
       (58, 'Veces que lo has visto usar Beso Drenaje'),
       (207, 'Veces que lo has visto usar Bofetón Lodo'),
       (155, 'Veces que lo has visto usar Bola Sombra'),
       (129, 'Veces que lo has visto usar Bomba Ácida'),
       (59, 'Veces que lo has visto usar Bomba Fango'),
       (133, 'Veces que lo has visto usar Bomba Lodo'),
       (206, 'Veces que lo has visto usar Brecha Negra'),
       (136, 'Veces que lo has visto usar Brillo Mágico'),
       (163, 'Veces que lo has visto usar Burbuja'),
       (145, 'Veces que lo has visto usar Cabeza de Hierro'),
       (60, 'Veces que lo has visto usar Cabezazo Zen'),
       (188, 'Veces que lo has visto usar Canto Helado'),
       (162, 'Veces que lo has visto usar Carantoña'),
       (61, 'Veces que lo has visto usar Carga Tóxica'),
       (139, 'Veces que lo has visto usar Chispa'),
       (62, 'Veces que lo has visto usar Chupavidas'),
       (186, 'Veces que lo has visto usar Chuzos'),
       (171, 'Veces que lo has visto usar Ciclón'),
       (179, 'Veces que lo has visto usar Clorofiláser'),
       (63, 'Veces que lo has visto usar Cola Férrea'),
       (185, 'Veces que lo has visto usar Colmillo Hielo'),
       (161, 'Veces que lo has visto usar Colmillo Ígneo'),
       (64, 'Veces que lo has visto usar Colmillo Rayo'),
       (182, 'Veces que lo has visto usar Condena Silvana'),
       (65, 'Veces que lo has visto usar Confusión'),
       (66, 'Veces que lo has visto usar Corpulencia'),
       (200, 'Veces que lo has visto usar Corte Vacío'),
       (67, 'Veces que lo has visto usar Cuchillada'),
       (137, 'Veces que lo has visto usar Danza Espada'),
       (68, 'Veces que lo has visto usar Danza Pétalo'),
       (130, 'Veces que lo has visto usar Danza Triunfal'),
       (175, 'Veces que lo has visto usar Defensa Férrea'),
       (69, 'Veces que lo has visto usar Descanso'),
       (199, 'Veces que lo has visto usar Distorsión'),
       (70, 'Veces que lo has visto usar Doble Filo'),
       (71, 'Veces que lo has visto usar Doble Golpe'),
       (128, 'Veces que lo has visto usar Energibola'),
       (174, 'Veces que lo has visto usar Enfado'),
       (164, 'Veces que lo has visto usar Envite Acuático'),
       (72, 'Veces que lo has visto usar Envite Ígneo'),
       (73, 'Veces que lo has visto usar Erupción de Ira'),
       (195, 'Veces que lo has visto usar Esfera Aural'),
       (74, 'Veces que lo has visto usar Espora'),
       (75, 'Veces que lo has visto usar Estoicismo'),
       (169, 'Veces que lo has visto usar Foco Resplandor'),
       (205, 'Veces que lo has visto usar Fogonazo'),
       (119, 'Veces que lo has visto usar Follaje'),
       (190, 'Veces que lo has visto usar Fuerza Equina'),
       (76, 'Veces que lo has visto usar Fuerza Lunar'),
       (173, 'Veces que lo has visto usar Garra Dragón'),
       (184, 'Veces que lo has visto usar Garra Nociva'),
       (201, 'Veces que lo has visto usar Garra Umbría'),
       (141, 'Veces que lo has visto usar Gas Venenoso'),
       (149, 'Veces que lo has visto usar Gigaimpacto'),
       (77, 'Veces que lo has visto usar Golpe Aéreo'),
       (78, 'Veces que lo has visto usar Golpe Roca'),
       (202, 'Veces que lo has visto usar Golpe Umbrío'),
       (79, 'Veces que lo has visto usar Hachazo Pétreo'),
       (158, 'Veces que lo has visto usar Hidroariete'),
       (125, 'Veces que lo has visto usar Hidrobomba'),
       (80, 'Veces que lo has visto usar Hidropulso'),
       (153, 'Veces que lo has visto usar Hiperrayo'),
       (81, 'Veces que lo has visto usar Hipnosis'),
       (82, 'Veces que lo has visto usar Hoja Aguda'),
       (121, 'Veces que lo has visto usar Hueso Sombrío'),
       (83, 'Veces que lo has visto usar Impactrueno'),
       (154, 'Veces que lo has visto usar Impresionar'),
       (156, 'Veces que lo has visto usar Infortunio'),
       (177, 'Veces que lo has visto usar Joya de Luz'),
       (84, 'Veces que lo has visto usar Lanzallamas'),
       (85, 'Veces que lo has visto usar Llama Embrujada'),
       (86, 'Veces que lo has visto usar Llamarada'),
       (122, 'Veces que lo has visto usar Lluevehojas'),
       (197, 'Veces que lo has visto usar Lluvia Ígnea'),
       (135, 'Veces que lo has visto usar Maquinación'),
       (123, 'Veces que lo has visto usar Marcha Espectral'),
       (150, 'Veces que lo has visto usar Mazazo'),
       (127, 'Veces que lo has visto usar Mil Púas Tóxicas'),
       (87, 'Veces que lo has visto usar Mimético'),
       (88, 'Veces que lo has visto usar Mordisco'),
       (192, 'Veces que lo has visto usar Nieve Polvo'),
       (89, 'Veces que lo has visto usar Ojitos Tiernos'),
       (168, 'Veces que lo has visto usar Onda Trueno'),
       (90, 'Veces que lo has visto usar Pájaro Osado'),
       (91, 'Veces que lo has visto usar Paralizador'),
       (92, 'Veces que lo has visto usar Paranormal'),
       (93, 'Veces que lo has visto usar Paz Mental'),
       (94, 'Veces que lo has visto usar Picotazo Veneno'),
       (151, 'Veces que lo has visto usar Placaje'),
       (208, 'Veces que lo has visto usar Plegaria Lunar'),
       (196, 'Veces que lo has visto usar Poder Místico'),
       (131, 'Veces que lo has visto usar Poder Pasado'),
       (95, 'Veces que lo has visto usar Polvo Veneno'),
       (96, 'Veces que lo has visto usar Psicocorte'),
       (97, 'Veces que lo has visto usar Psíquico'),
       (146, 'Veces que lo has visto usar Pulso Dragón'),
       (98, 'Veces que lo has visto usar Pulso Umbrío'),
       (99, 'Veces que lo has visto usar Puño Bala'),
       (167, 'Veces que lo has visto usar Puño Fuego'),
       (170, 'Veces que lo has visto usar Puño Trueno'),
       (166, 'Veces que lo has visto usar Puya Nociva'),
       (100, 'Veces que lo has visto usar Rayo'),
       (160, 'Veces que lo has visto usar Rayo Carga'),
       (101, 'Veces que lo has visto usar Rayo Hielo'),
       (102, 'Veces que lo has visto usar Recuperación'),
       (193, 'Veces que lo has visto usar Rencor Reprimido'),
       (120, 'Veces que lo has visto usar Respiro'),
       (147, 'Veces que lo has visto usar Retracción'),
       (103, 'Veces que lo has visto usar Rodar'),
       (104, 'Veces que lo has visto usar Rueda Fuego'),
       (105, 'Veces que lo has visto usar Salpicadura'),
       (211, 'Veces que lo has visto usar Simún de Arena'),
       (124, 'Veces que lo has visto usar Sofoco'),
       (106, 'Veces que lo has visto usar Tajo Aéreo'),
       (126, 'Veces que lo has visto usar Tajo Metralla'),
       (107, 'Veces que lo has visto usar Teletransporte'),
       (142, 'Veces que lo has visto usar Terratemblor'),
       (187, 'Veces que lo has visto usar Testarazo'),
       (178, 'Veces que lo has visto usar Tierra Viva'),
       (108, 'Veces que lo has visto usar Tijera X'),
       (109, 'Veces que lo has visto usar Tornado'),
       (110, 'Veces que lo has visto usar Trampa Rocas'),
       (152, 'Veces que lo has visto usar Triataque'),
       (210, 'Veces que lo has visto usar Triple Flecha'),
       (111, 'Veces que lo has visto usar Triturar'),
       (112, 'Veces que lo has visto usar Trueno'),
       (113, 'Veces que lo has visto usar Veneno X'),
       (114, 'Veces que lo has visto usar Vendaval'),
       (159, 'Veces que lo has visto usar Ventisca'),
       (180, 'Veces que lo has visto usar Viento Aciago'),
       (191, 'Veces que lo has visto usar Viento Carámbano'),
       (115, 'Veces que lo has visto usar Viento Feérico'),
       (116, 'Veces que lo has visto usar Viento Plata'),
       (117, 'Veces que lo has visto usar Voltio Cruel'),
       (118, 'Veces que lo has visto usar Zumbido');
