CREATE TABLE areas
(
    id   INTEGER     NOT NULL,
    name VARCHAR(20) NOT NULL,
    CONSTRAINT pk_areas PRIMARY KEY (id)
);

INSERT INTO areas (id, name)
VALUES (0, 'COASTLANDS'),
       (1, 'DISTORTION'),
       (2, 'FIELDLANDS'),
       (3, 'HIGHLANDS'),
       (4, 'ICELANDS'),
       (5, 'MIRELANDS');

CREATE TABLE locations
(
    id   INTEGER     NOT NULL,
    name VARCHAR(30) NOT NULL,
    area INTEGER     NOT NULL,
    CONSTRAINT pk_locations PRIMARY KEY (id)
);

INSERT INTO locations (id, name, area)
VALUES (0, 'Alacena del Bosque', 2),
       (1, 'Arena del Gran Árbol', 2),
       (2, 'Bosque Recóndito', 2),
       (3, 'Campo Aromaflor', 2),
       (4, 'Cascada Obsidiana', 2),
       (5, 'Colina del Anhelo', 2),
       (6, 'Foresta Funesta', 2),
       (7, 'Gruta Pirita', 2),
       (8, 'Isla Hansa', 2),
       (9, 'Lago Veraz', 2),
       (10, 'Loma del Venado', 2),
       (11, 'Planicie Arena', 2),
       (12, 'Prado Herradura', 2),
       (13, 'Presa del Estuario', 2),
       (14, 'Puente Erosionado', 2),
       (15, 'Senda del Venado', 2),
       (16, 'Vereda del Viento', 2),
       (17, 'Arena del Escenario', 5),
       (18, 'Banco del Juicio', 5),
       (19, 'Caverna del Valor', 5),
       (20, 'Ciénaga Bermeja', 5),
       (21, 'Ciénaga Bocazas', 5),
       (22, 'Ladera Derrumbe', 5),
       (23, 'Lago Valor', 5),
       (24, 'Llanura Diamante', 5),
       (25, 'Loma Lodosa', 5),
       (26, 'Palestra Ursa', 5),
       (27, 'Poblado Diamante', 5),
       (28, 'Pradera Aleteo', 5),
       (29, 'Pradera Áurea', 5),
       (30, 'Prado Erióforo', 5),
       (31, 'Rellano Nebuloso', 5),
       (32, 'Ruinas de la Niebla', 5),
       (33, 'Ruinas Sosiego', 5),
       (34, 'Albuferas Chapuzón', 0),
       (35, 'Altar Domo Lava', 0),
       (36, 'Arboleda Tétrica', 0),
       (37, 'Arena del Magma', 0),
       (38, 'Bahía Silente', 0),
       (39, 'Bosque Rompeviento', 0),
       (40, 'Cabo Rocavelo', 0),
       (41, 'Cala Oculta', 0),
       (42, 'Camino del Tómbolo', 0),
       (43, 'Cerro Aipom', 0),
       (44, 'Costa Ínsola', 0),
       (45, 'Cueva Costera', 0),
       (46, 'Cueva Retorno', 0),
       (47, 'Gruta Pasamar', 0),
       (48, 'Guarida del Gran Pez', 0),
       (49, 'Isla Escupefuego', 0),
       (50, 'Mano de Arena', 0),
       (51, 'Paso Costanero', 0),
       (52, 'Playa del Errante', 0),
       (53, 'Playa Ginkgo', 0),
       (54, 'Vergel Marino', 0),
       (55, 'Vía Manantial', 0),
       (56, 'Ágora de la Plegaria', 3),
       (57, 'Arena de la Luna', 3),
       (58, 'Bosque Extravío', 3),
       (59, 'Cañón Lítico', 3),
       (60, 'Cantera Ancestral', 3),
       (61, 'Caverna Inmemorial', 3),
       (62, 'Columnas Lanza', 3),
       (63, 'Cordillera Derrumbe', 3),
       (64, 'Cueva Extravío', 3),
       (65, 'Fuente de las Hadas', 3),
       (66, 'Loma Sagrada', 3),
       (67, 'Manantial Solitario', 3),
       (68, 'Paso Píleo', 3),
       (69, 'Risco Riscoso', 3),
       (70, 'Ruinas Celestiales', 3),
       (71, 'Senda Celestial', 3),
       (72, 'Senda del Peregrino', 3),
       (73, 'Templo de Sinnoh', 3),
       (74, 'Umbral Pétreo', 3),
       (75, 'Arena del Glaciar', 4),
       (76, 'Cascada Glaliar', 4),
       (77, 'Caverna Agudeza', 4),
       (78, 'Caverna Hiberna', 4),
       (79, 'Desfiladero Alud', 4),
       (80, 'Lago Agudeza', 4),
       (81, 'Páramo Algente', 4),
       (82, 'Pasaje de la Grieta', 4),
       (83, 'Peñasco Espíritu', 4),
       (84, 'Poblado Perla', 4),
       (85, 'Senda de la Arena', 4),
       (86, 'Témpano Avalugg', 4),
       (87, 'Templo Puntaneva', 4),
       (88, 'Termas Nevavista', 4),
       (89, 'Terraza Glaciar', 4),
       (90, 'Tundra Alba', 4),
       (91, 'Valle Nevasca', 4),
       (92, 'Distorsión espaciotemporal', 1);
